### PR TITLE
Add argo workflows

### PR DESCRIPTION
**Pull request by amarrella**
This PR add dhall types and defaults for [argo](https://github.com/argoproj/argo) v2.3.0

The types have been generated from the [swagger spec](https://github.com/argoproj/argo/blob/v2.3.0/api/openapi-spec/swagger.json) using [dhall-kubernetes-generator](https://github.com/dhall-lang/dhall-kubernetes) (specifically the version in this [pending PR](https://github.com/dhall-lang/dhall-kubernetes/pull/84) which also generate records that support the new syntax).

The following manual interventions were necessary to make it compile:
- add all the `io.k8s` files that you find in the types directory. These reference dhall-kubernetes
- remove `status` from the `Workflow` type (status is fine on read but we shouldn't be using it on write)
- Fix a wrong type in https://github.com/EarnestResearch/dhall-packages/compare/argo-workflows?expand=1#diff-109e272af4e76ca2072c697c209477a8R24 (it was referencing the wrong directory).

Long term plan is to probably directly fork and make dhall-kubernetes-generator do all this work.

Note: the types generated from the swagger spec are not perfect (e.g. use optional instead of union types) but since they are generated they are easier to maintain. We should build on top of these a higher level library for argo/kubeflow.

### CODE REVIEW

**Comment by amarrella** [comment]
@retnuh good idea! I created a diff file now. It's a bit noisy due to all the freeze also happening, but it gives a better idea of every change happened (including the import freezing)

**Comment by retnuh** [comment]
I don't think it matters here, and I obviously thought of it too late, but maybe in the future for things of this nature, it would make sense to have multiple patches - one for each of the discrete or logical changes.  For example, one that was the freezing; another for removing the status, etc.  🤔

**Comment by amarrella** [comment]
@retnuh good point. I will try to do it better next time (also with a more granular commit history)

**Comment by retnuh** [comment]
Or maybe just do the intermittent commits, and not worry about saving the diffs; just keep the git history (i.e. don't squash the merge)?  Then we can let git do the diffing if we need it...

**Pull request merged**
